version: "3"
services:
    #MySQL Service
    ci-test-db:
        image: mysql:5.7.22
        container_name: ci-test-db
        restart: unless-stopped
        tty: true
        ports:
            - "13307:3306"
        volumes:
            - dbdata:/var/lib/mysql/
            - ./docker/mysql/conf/mysql-docker.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_DATABASE: database
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
